language: minimal
sudo: false

env:
    - PY=3.6 PYSAL_PYPI=true PYSAL_PLUS=true
    - PY=3.6 PYSAL_PYPI=true PYSAL_PLUS=false
    - PY=3.6 PYSAL_PYPI=false PYSAL_PLUS=true
    - PY=3.6 PYSAL_PYPI=false PYSAL_PLUS=false
    - PY=3.7 PYSAL_PYPI=true PYSAL_PLUS=true
    - PY=3.7 PYSAL_PYPI=true PYSAL_PLUS=false
    - PY=3.7 PYSAL_PYPI=false PYSAL_PLUS=true
    - PY=3.7 PYSAL_PYPI=false PYSAL_PLUS=false

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.6
      env: PYSAL_PYPI=false PYSAL_PLUS=false
    - python: 3.6
      env: PYSAL_PYPI=false PYSAL_PLUS=true
    - python: 3.7
      env: PYSAL_PYPI=false PYSAL_PLUS=false
    - python: 3.7
      env: PYSAL_PYPI=false PYSAL_PLUS=true

before_install:
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update --quiet conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda config --set safety_checks disabled
    conda create --name TEST python=$PY --file requirements.txt --file requirements_dev.txt --file requirements_docs.txt --file requirements_tests.txt
    source activate TEST
    conda info --all

install:
  - if "$PYSAL_PYPI"; then
        echo 'testing conda libpysal' && conda install --yes libpysal;
        else echo 'testing git libpysal';
        git clone https://github.com/pysal/libpysal.git;
        cd libpysal; pip install .; cd ../;
    fi;
  - if [ "$PYSAL_PLUS" == true ]; then
        echo 'plus testing'; conda install --yes --file requirements_plus.txt;
    fi;

script:
  - python setup.py sdist >/dev/null
  - nosetests --verbose --with-doctest --with-coverage --cover-package=spaghetti;

notifications:
    email:
        recipients:
          - sjsrey@gmail.com
          - levi.john.wolf@gmail.com
          - jgaboardi@gmail.com
        on_success: change
        on_failure: change

after_success:
  - coveralls
