codecov:
  notify:
   after_n_builds: 24

coverage:
  range: 50..95
  round: nearest
  precision: 1
  status:
    project:
      default:
        against: parent
        target: auto
        threshold: 2%
        branches:
        - master
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
        - integration
        paths:
        - folder
    patch:
      default:
        against: parent
        target: 80%
        branches: null
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder
    changes:
      default:
        against: parent
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder
  ignore:
    - "tests/*"
comment:
  layout: "reach, diff, flags, files"
  branches: *
  behavior: default
  after_n_builds: 24
