name: docs
channels:
  - conda-forge
dependencies:
  - python=3.6
  - rtree
  - geopandas
  - pip:
    - esda>=2.0.0
    - sphinx>=1.4.3
    - sphinxcontrib-bibtex
    - sphinx_bootstrap_theme
    - numpydoc
    - nose
    - nose-progressive
    - coverage
    - coveralls
    - matplotlib
    - scipy>=0.11
    - numpy>=1.3
    - pandas
