name: test-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - geopandas
  - rtree
  - libspatialindex
  - pulp
  - esda
  - matplotlib
  - watermark
  - seaborn
  - pip:
    - ortools
    - "--editable=git+https://github.com/pysal/spaghetti.git@master"
