 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'

 jobs:
   conda_3637_allos:
     name: conda (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.environment-file }})
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
         python-version: ['3.6', '3.7']
         environment-file: [ci/travis/36-latest-conda-forge-PYPI.yaml, ci/travis/36-latest-conda-forge-PYPI-PLUS.yaml, ci/travis/37-latest-conda-forge-PYPI.yaml, ci/travis/37-latest-conda-forge-PYPI-PLUS.yaml]
     steps:
       - uses: actions/checkout@v2
       - uses: goanpeca/setup-miniconda@v1
         with:
            miniconda-version: 'latest'
            auto-update-conda: true
            auto-activate-base: false
            environment-file: ${{ matrix.environment-file }}
            activate-environment: test
       - shell: bash -l {0}
         run: |
           conda info --all;
           conda list;
           py.test -v spaghetti --cov=spaghetti --doctest-modules --cov-config=.coveragerc --cov-report=xml;
       - name: codecov (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.environment-file }})
         uses: codecov/codecov-action@v1
         with:
           file: ./coverage.xml
           flags: unittests
           name: codecov-umbrella
   #conda_38:
   #  name: conda (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.environment-file }})
   #  runs-on: ${{ matrix.os }}
   #  strategy:
   #    matrix:
   #      os: [ubuntu-latest]
   #      python-version: [3.8]
   #      environment-file: [ci/38-latest-conda-forge-PYPI.yaml]
   #  steps:
   #    - uses: actions/checkout@v2
   #    - uses: goanpeca/setup-miniconda@v1
   #      with:
   #         miniconda-version: 'latest'
   #         python-version: ${{ matrix.python-version }}
   #         auto-update-conda: true
   #         auto-activate-base: false
   #         environment-file: ${{ matrix.environment-file }}
   #         activate-environment: test
   #    - shell: bash -l {0}
   #      run: |
   #        conda info
   #        conda list
   #        python setup.py install
   #        py.test -v spaghetti --doctest-modules



