 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'
   schedule:
     - cron: '59 23 * * *'

 jobs:
   unittests:
     name: micromamba unittests (${{ matrix.os }}, ${{ matrix.environment-file }})
     runs-on: ${{ matrix.os }}
     timeout-minutes: 30
     strategy:
       matrix:
         os: [macos-latest, ubuntu-latest, windows-latest]
         environment-file: [ci/36.yaml, ci/37.yaml, ci/38.yaml, ci/39.yaml, ci/39-BASE.yaml]
         exclude:
           - environment-file: ci/36.yaml
             os: windows-latest
           - environment-file: ci/39-BASE.yaml
             os: macos-latest
           - environment-file: ci/39-BASE.yaml
             os: windows-latest
           
     steps:
       - name: checkout repo
         uses: actions/checkout@v2
       
       - name: setup micromamba
         uses: mamba-org/provision-with-micromamba@main
         with:
           environment-file: ${{ matrix.environment-file }}
           micromamba-version: 'latest'
      
       - name: install bleeding edge libpysal - bash
         shell: bash -l {0}
         run: pip install git+https://github.com/pysal/libpysal.git@master
         if: matrix.os != 'windows-latest'
      
       - name: install bleeding edge libpysal - powershell
         shell: powershell
         run: pip install git+https://github.com/pysal/libpysal.git@master
         if: matrix.os == 'windows-latest'
       
       - name: run tests - bash
         shell: bash -l {0}
         run: pytest -v spaghetti --cov=spaghetti --doctest-modules --cov-config=.coveragerc --cov-report=xml
         if: matrix.os != 'windows-latest'
       
       - name: run tests - powershell
         shell: powershell
         run: pytest -v spaghetti --cov=spaghetti --doctest-modules --cov-config=.coveragerc --cov-report=xml
         if: matrix.os == 'windows-latest'
       
       - name: codecov
         uses: codecov/codecov-action@v1
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: ./coverage.xml
           name: spaghetti-codecov
